version: '3.8'
services:
  app:
    image: go.0.1
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_URI=${MONGO_URI}
      - DB_NAME=${DB_NAME}
    ports:
      - "4455:8080"
